In [23]:
# Pandas is powerful and useful library used for data analyis
import pandas as pd
nba_df = pd.read_csv('nba.csv')
print(nba_df.head()) # Top 5 rows
print(nba_df.tail()) # Last 5 rows
print('Rows and Colns',nba_df.shape)
print('Data Type',nba_df.dtypes)
print('Describe',nba_df.describe())
print('Name')
print(nba_df.Name.head())
print('Multiple columns')
print(nba_df[['Name', 'Team', 'Salary']].head())
nba_df[ (nba_df.Team == 'Boston Celtics') & (nba_df.Age <= 25) ]

            Name            Team  Number Position   Age Height  Weight  \
0  Avery Bradley  Boston Celtics     0.0       PG  25.0    6-2   180.0
1    Jae Crowder  Boston Celtics    99.0       SF  25.0    6-6   235.0
2   John Holland  Boston Celtics    30.0       SG  27.0    6-5   205.0
3    R.J. Hunter  Boston Celtics    28.0       SG  22.0    6-5   185.0
4  Jonas Jerebko  Boston Celtics     8.0       PF  29.0   6-10   231.0

             College     Salary
0              Texas  7730337.0
1          Marquette  6796117.0
2  Boston University        NaN
3      Georgia State  1148640.0
4                NaN  5000000.0
             Name       Team  Number Position   Age Height  Weight College  \
453  Shelvin Mack  Utah Jazz     8.0       PG  26.0    6-3   203.0  Butler
454     Raul Neto  Utah Jazz    25.0       PG  24.0    6-1   179.0     NaN
455  Tibor Pleiss  Utah Jazz    21.0        C  26.0    7-3   256.0     NaN
456   Jeff Withey  Utah Jazz    24.0        C  26.0    7-0   231.0  Kansas
457           NaN        NaN     NaN      NaN   NaN    NaN     NaN     NaN

        Salary
453  2433333.0
454   900000.0
455  2900000.0
456   947276.0
457        NaN
Rows and Colns (458, 9)
Data Type Name         object
Team         object
Number      float64
Position     object
Age         float64
Height       object
Weight      float64
College      object
Salary      float64
dtype: object
Describe            Number         Age      Weight        Salary
count  457.000000  457.000000  457.000000  4.460000e+02
mean    17.678337   26.938731  221.522976  4.842684e+06
std     15.966090    4.404016   26.368343  5.229238e+06
min      0.000000   19.000000  161.000000  3.088800e+04
25%      5.000000   24.000000  200.000000  1.044792e+06
50%     13.000000   26.000000  220.000000  2.839073e+06
75%     25.000000   30.000000  240.000000  6.500000e+06
max     99.000000   40.000000  307.000000  2.500000e+07
Name
0    Avery Bradley
1      Jae Crowder
2     John Holland
3      R.J. Hunter
4    Jonas Jerebko
Name: Name, dtype: object
Multiple columns
            Name            Team     Salary
0  Avery Bradley  Boston Celtics  7730337.0
1    Jae Crowder  Boston Celtics  6796117.0
2   John Holland  Boston Celtics        NaN
3    R.J. Hunter  Boston Celtics  1148640.0
4  Jonas Jerebko  Boston Celtics  5000000.0

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
0,Avery Bradley,Boston Celtics,0.0,PG,25.0,6-2,180.0,Texas,7730337.0
1,Jae Crowder,Boston Celtics,99.0,SF,25.0,6-6,235.0,Marquette,6796117.0
3,R.J. Hunter,Boston Celtics,28.0,SG,22.0,6-5,185.0,Georgia State,1148640.0
6,Jordan Mickey,Boston Celtics,55.0,PF,21.0,6-8,235.0,LSU,1170960.0
7,Kelly Olynyk,Boston Celtics,41.0,C,25.0,7-0,238.0,Gonzaga,2165160.0
8,Terry Rozier,Boston Celtics,12.0,PG,22.0,6-2,190.0,Louisville,1824360.0
9,Marcus Smart,Boston Celtics,36.0,PG,22.0,6-4,220.0,Oklahoma State,3431040.0
10,Jared Sullinger,Boston Celtics,7.0,C,24.0,6-9,260.0,Ohio State,2569260.0
13,James Young,Boston Celtics,13.0,SG,20.0,6-6,215.0,Kentucky,1749840.0

In [24]:
nba_df.sort_values(by = 'Weight', ascending = False)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
405,Nikola Pekovic,Minnesota Timberwolves,14.0,C,30.0,6-11,307.0,NaN,12100000.0
302,Boban Marjanovic,San Antonio Spurs,40.0,C,27.0,7-3,290.0,NaN,1200000.0
330,Al Jefferson,Charlotte Hornets,25.0,C,31.0,6-10,289.0,NaN,13500000.0
395,Jusuf Nurkic,Denver Nuggets,23.0,C,21.0,7-0,280.0,NaN,1842000.0
188,Andre Drummond,Detroit Pistons,0.0,C,22.0,6-11,279.0,Connecticut,3272091.0
...,...,...,...,...,...,...,...,...,...
359,Brandon Jennings,Orlando Magic,55.0,PG,26.0,6-1,169.0,NaN,8344497.0
263,Bryce Cotton,Memphis Grizzlies,8.0,PG,23.0,6-1,165.0,Providence,700902.0
350,Briante Weber,Miami Heat,12.0,PG,23.0,6-2,165.0,Virginia Commonwealth,NaN
152,Aaron Brooks,Chicago Bulls,0.0,PG,31.0,6-0,161.0,Oregon,2250000.0
457,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [30]:
nba_df[ (nba_df.Team == 'Memphis Grizzlies') & (nba_df.Position == 'PG')].sort_values(by='Salary', ascending = False).head(1)

,Name,Team,Number,Position,Age,Height,Weight,College,Salary
262,Mike Conley,Memphis Grizzlies,11.0,PG,28.0,6-1,175.0,Ohio State,9588426.0